### ISSUE TITLE
Do the correct number of checks after restart

### ISSUE THREAD

**Issue by Artraxon** [Artraxon/unexBot#10]
Currently, if a post is in the time window where a check would have to take place, after a restart it does all checks again.
It's not really a big issue since restarts should be very rare.

**Comment by earthshakira** [comment]
Hi! I'd like to work on this issue could you please add some more information about this

**Comment by Artraxon** [comment]
Oh, I'm terribly sorry that I didn't answer, I was quite busy in February and then forgot to answer afterwards:
I'm planning to introduce a more general checkpoint facility, that can be used in the Flow to generate automatic snapshots from which things can be restarted. I'm currently planning to introduce a lot of refactoring so I don't think it makes sense at the moment to implement this feature specifically for unexbot since it would have to be re-implemented for other bots as well.
