### ISSUE TITLE
Censored word cannot be uncensored

### ISSUE THREAD

**Issue by H4XKER** [Artraxon/unexBot#17]
For some reason in my reddit everytime i tried to uncensored the word it not working i need to click it multiple time in order to uncensored it. In the past i uncensored with just one click but nowday it not work help. 

Here is full video you can try look at it since github doesn't allow you to send MP4 file format: https://streamable.com/vtwoml

**Comment by Artraxon** [comment]
To my eyes this looks like a problem with the client, I'd suggest reporting the bug to reddit themselves. 
[The lay out the process here](https://reddit.zendesk.com/hc/en-us/articles/205687083-How-do-I-report-a-bug-l).
