### ISSUE TITLE
Bot has not been working for 4 days.

### ISSUE THREAD

**Issue by qfaq** [Artraxon/unexBot#8]
If you look at the unexBot account it has not posted in around 4 days. Offline? Something happen?

**Comment by Artraxon** [comment]
yes, we had some problems with the server the bot is running on (there was a service that ate up all the memory) and set it up new (was time for a cleanup anyway :D).
As soon as the Bot is readded as mod, I'll start it again. u/unexBot is already up and running
Edit: Didn't realize this was on unexBot site, so, yes, unexbot is up and running again.
